"""`make doc-serve` wrapper that watches the source config files.

What this solves
----------------

`mkdocs.yml` in projects using this template is *autogenerated* by
`setup_documentation.py` from `mkdocs_custom.yml` (project-specific) plus
`mkdocs_base.yml` (shipped from this template). `mkdocs serve --livereload`
natively watches `docs/` and `mkdocs.yml`, but never sees edits to either
source file — you'd otherwise need to ctrl-c and rerun the make target
after every config change.

This wrapper closes that gap. It watches both source files; on change it
re-runs `setup_documentation.py`, which rewrites `mkdocs.yml` — and
`mkdocs serve`'s built-in watcher then sees the regenerated file and
triggers a full reload.

It also passes `--livereload` explicitly because `mkdocs serve` in
mkdocs 1.6 + Click 8 silently defaults to *no* live reload when the flag
is omitted (the paired --livereload/--no-livereload Click options resolve
to False if neither is passed). Without this, edits to `docs/` itself
also wouldn't reload.

How it's invoked
----------------

The shipped Makefile target wires it up::

    doc-serve:
        uv sync --project $(MKDOCS_ENV)
        uv run --project $(MKDOCS_ENV) python $(MKDOCS_ENV)/setup_documentation.py
        uv run --project $(MKDOCS_ENV) python $(MKDOCS_ENV)/doc_serve_watch.py

Notes
-----

- `watchdog` is a transitive dependency of mkdocs, so no extra install.
- Hot-reloading the hook code itself requires a wrapper restart: mkdocs
  caches loaded hook modules with `functools.lru_cache` keyed by class-
  level singletons. Edit a hook's `.py` and you may need to ctrl-c +
  `make doc-serve` again. Edits to `mkdocs_custom.yml`, `.mailmap` and
  `docs/authors.yml` are picked up live with no restart needed.
"""

from __future__ import annotations

import signal
import subprocess
import sys
import time
from pathlib import Path

from watchdog.events import FileSystemEventHandler
from watchdog.observers import Observer

# This file is shipped at <project>/.make_scripts/mkdocs-documentation/doc_serve_watch.py
# so the project root is two levels up.
MKDOCS_ENV = Path(__file__).resolve().parent
REPO_ROOT = MKDOCS_ENV.parent.parent
SETUP = MKDOCS_ENV / "setup_documentation.py"
SOURCES = [
    REPO_ROOT / "mkdocs_custom.yml",
    MKDOCS_ENV / "mkdocs_base.yml",
]


def regen() -> None:
    print("[doc-serve] regenerating mkdocs.yml ...", flush=True)
    subprocess.run(
        ["uv", "run", "--project", str(MKDOCS_ENV), "python", str(SETUP)],
        cwd=REPO_ROOT,
        check=False,
    )


class SourceHandler(FileSystemEventHandler):
    def __init__(self) -> None:
        self._last = 0.0
        self._sources = {p.resolve() for p in SOURCES}

    def _fire_if_source(self, path: str) -> None:
        if Path(path).resolve() not in self._sources:
            return
        # Debounce — editors often emit two events per save.
        now = time.monotonic()
        if now - self._last < 0.3:
            return
        self._last = now
        regen()

    def on_modified(self, event) -> None:  # type: ignore[override]
        if not event.is_directory:
            self._fire_if_source(event.src_path)

    def on_created(self, event) -> None:  # type: ignore[override]
        if not event.is_directory:
            self._fire_if_source(event.src_path)

    def on_moved(self, event) -> None:  # type: ignore[override]
        # Atomic-rename writes (vim, many IDEs, agent edit tools) deliver the
        # saved content as a move whose dest_path is the watched file.
        if not event.is_directory:
            self._fire_if_source(getattr(event, "dest_path", event.src_path))


def main() -> int:
    handler = SourceHandler()
    observer = Observer()
    for d in {p.parent.resolve() for p in SOURCES}:
        observer.schedule(handler, str(d), recursive=False)
    observer.start()

    serve = subprocess.Popen(
        ["uv", "run", "--project", str(MKDOCS_ENV),
         "mkdocs", "serve", "--livereload"],
        cwd=REPO_ROOT,
    )
    try:
        return serve.wait()
    except KeyboardInterrupt:
        return 0
    finally:
        if serve.poll() is None:
            serve.send_signal(signal.SIGINT)
            try:
                serve.wait(timeout=5)
            except subprocess.TimeoutExpired:
                serve.terminate()
        observer.stop()
        observer.join()


if __name__ == "__main__":
    sys.exit(main())
