from pathlib import Path

import deepmerge
import yaml
import subprocess
import os
import shutil

MKDOCS_BASE = ".make_scripts/mkdocs-documentation/mkdocs_base.yml"
MKDOCS_CUST_TEMPLATE = ".make_scripts/mkdocs-documentation/mkdocs_custom.yml"
MKDOCS_DOCS_TEMPLATE = ".make_scripts/mkdocs-documentation/docs_template"

MKDOCS_CUST = "mkdocs_custom.yml"
MKDOCS_RES = "mkdocs.yml"

RES_HEADER = """# 
# -------------------------------------------
# 
# THIS FILE IS AUTOGENERATED, DO NOT EDIT!
# Instead, perform your changes or extensions (to mkdocs_base.yml) in mkdocs_custom.yml
# These files will be merged together into mkdocs.yml (this file)
# 
# -------------------------------------------
# 
"""


class SafeLoaderIgnoreUnknown(yaml.SafeLoader):
    """
    A safe loader that passes unknown values through unchanged
    """

    def pass_unknown(self, node):
        return node.tag


def is_file_dirty(filename):
    """
    Checks if a specific file is dirty (modified but not staged) in the Git index.
    Returns False if the file doesn't exist or is not in a Git repository.

    Args:
        filename: The path to the file to check.

    Returns:
        True if the file is dirty, False otherwise.
    """
    # 1. Check if file exists first
    if not os.path.exists(filename):
        return False

    # 2. Check if we are inside a Git repository
    # rev-parse returns 0 if inside a repo, non-zero otherwise
    is_git = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"], capture_output=True, text=True)
    if is_git.returncode != 0:
        return False

    # 3. Run git diff-index to compare the working tree with the index
    # We redirect stderr to DEVNULL to suppress "not a git repo" or other Git errors
    command = ["git", "diff-index", "--quiet", "--cached", "HEAD", filename]
    result = subprocess.run(command, stderr=subprocess.DEVNULL)

    # Check the returncode. Non-zero indicates a difference (dirty file)
    return result.returncode != 0


def read_file(file_name):
    with open(file_name) as f:
        return f.read()


def write_file(file_name, content):
    with open(file_name, "w") as f:
        f.write(content)


def merge_mkdocs_yml():
    SafeLoaderIgnoreUnknown.add_constructor(None, SafeLoaderIgnoreUnknown.pass_unknown)

    yaml_base = yaml.load(read_file(MKDOCS_BASE), Loader=SafeLoaderIgnoreUnknown)
    yaml_custom = yaml.load(read_file(MKDOCS_CUST), Loader=SafeLoaderIgnoreUnknown)

    yaml_res = deepmerge.always_merger.merge(yaml_base, yaml_custom)

    if not is_file_dirty(MKDOCS_RES):
        write_file(
            MKDOCS_RES,
            RES_HEADER + yaml.dump(yaml_res).replace("tag:yaml.org,2002:", "!!").replace("'!relative'", "!relative"),
        )
    else:
        raise Exception(f"{MKDOCS_RES} is dirty, stage or commit first")


def ensure_mkdocs_custom():
    if not os.path.exists(MKDOCS_CUST):
        shutil.copy(MKDOCS_CUST_TEMPLATE, MKDOCS_CUST)


def ensure_docs_dir():
    """
    Ensures that the docs directory exists and contains an index.md.
    If not, create it with an index.md
    """

    if not os.path.exists("docs"):
        shutil.copytree(MKDOCS_DOCS_TEMPLATE, "docs")


# Files under docs_template/ that are *managed* by this pipeline — they get
# pushed into every project's docs/ tree on every setup run, overwriting any
# local copy. Use this for shared styling / assets that should stay in sync
# across all neops projects (e.g. content-tab CSS).
#
# Project-specific overrides should live under a different filename so they
# aren't clobbered (e.g. docs/assets/project-extra.css, with both files
# referenced from extra_css in the project's mkdocs_custom.yml).
MANAGED_DOCS_ASSETS = [
    "assets/extra.css",
    "assets/extra.js",
]


def sync_managed_docs_assets():
    """
    Copy each MANAGED_DOCS_ASSETS file from docs_template/ into the project's
    docs/ tree, creating any missing parent directories. Runs unconditionally
    so existing projects pick up upstream styling fixes via `make doc-update-assets`.
    """
    for rel_path in MANAGED_DOCS_ASSETS:
        src = os.path.join(MKDOCS_DOCS_TEMPLATE, rel_path)
        dst = os.path.join("docs", rel_path)
        if not os.path.exists(src):
            # Defensive: skip silently if the upstream template doesn't ship
            # this asset (e.g. older release before the file was added).
            continue
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy(src, dst)
        print(f"++ Synced managed asset: {dst}")


# Base directory of the installed template tooling.
MKDOCS_ENV_DIR = ".make_scripts/mkdocs-documentation"

# Generic starter files seeded into a project ONLY if they don't already exist —
# never overwritten, so a project's own authors / mailmap edits are safe. These
# carry project-specific content (the author-display feature), so we ship empty,
# commented skeletons for the project to fill in.
#   template source (relative to MKDOCS_ENV_DIR) -> project destination
SEED_FILES = {
    "docs_template/authors.yml": "docs/authors.yml",
    "templates/mailmap": ".mailmap",
}

# Lines ensured present in the project's root .gitignore. The document-dates
# plugin regenerates docs/assets/document_dates/user.config.{js,css} on every
# build from its own commented defaults, so they shouldn't be committed.
GITIGNORE_ENTRIES = [
    "docs/assets/document_dates/",
]


def seed_files():
    """
    Copy each SEED_FILES entry into the project, but only when the destination
    doesn't already exist. Lets new projects start from a working skeleton while
    leaving any project that has already customised these files untouched.
    """
    for rel_src, dst in SEED_FILES.items():
        src = os.path.join(MKDOCS_ENV_DIR, rel_src)
        if not os.path.exists(src):
            # Older release that doesn't ship this starter — skip silently.
            continue
        if os.path.exists(dst):
            continue
        parent = os.path.dirname(dst)
        if parent:
            os.makedirs(parent, exist_ok=True)
        shutil.copy(src, dst)
        print(f"++ Seeded starter file: {dst}")


def ensure_gitignore_entries():
    """
    Append any missing GITIGNORE_ENTRIES to the project's root .gitignore,
    creating the file if necessary. Idempotent: existing lines are left alone.
    """
    gitignore = ".gitignore"
    existing = []
    if os.path.exists(gitignore):
        existing = read_file(gitignore).splitlines()

    missing = [entry for entry in GITIGNORE_ENTRIES if entry not in existing]
    if not missing:
        return

    prefix = ""
    if existing and existing[-1].strip() != "":
        prefix = "\n"
    with open(gitignore, "a") as f:
        f.write(prefix + "\n".join(missing) + "\n")
    for entry in missing:
        print(f"++ Added .gitignore entry: {entry}")


def is_ignored_by_git(path):
    # Use git check-ignore command to see if the path is ignored
    result = subprocess.run(["git", "check-ignore", path], capture_output=True, text=True)

    # If the result's stdout is not empty, the path is ignored
    return result.stdout != ""


def create_symlinks():
    """
    Create symlinks for all folders in the root of the directory to enable snippets in the documentation
    Note that you should not reference files outside of the docs dir (i.e., do not use ../folder/file),
    as this will lead to an error when composing multiple docs
    :return:
    """
    path = "."
    directories = [d for d in os.listdir(path) if os.path.isdir(os.path.join(path, d))]

    config = yaml.load(read_file(MKDOCS_RES), Loader=SafeLoaderIgnoreUnknown)

    docs_dir = Path(config.get("docs_dir", "./docs"))

    symlinks = [f for f in docs_dir.iterdir() if f.is_symlink()]

    additional_ignores: list[str] = []
    symlink_path = f"{docs_dir}/.symlinkignore"
    try:
        additional_ignores = read_file(symlink_path).split("\n")
        print("Found .symlinkignore file")
    except FileNotFoundError:
        print(f"No .symlinkignore file found at {symlink_path}")

    for line in additional_ignores:
        print(f"symlinkignore Line: {line}")

    for dir in directories:
        if dir in additional_ignores:
            print(f"-- Skipping {dir} (.symlinkignore-ignored)")
            continue
        if is_ignored_by_git(dir):
            print(f"-- Skipping {dir} (git-ignored)")
            continue
        if dir.startswith("."):
            print(f"-- Skipping {dir} (hidden directory)")
            continue
        if dir.startswith("node_modules"):
            print(f"-- Skipping {dir} (node_modules)")
            continue
        if dir.startswith("make_scripts"):
            print(f"-- Skipping {dir} (node_modules)")
            continue
        if dir.startswith("submodules"):
            print(f"-- Skipping {dir} (submodules need to be referenced directly)")
            continue
        if dir.endswith(docs_dir.name):
            print(f"-- Skipping {dir} (docs directory)")
            continue
        else:
            dest = f"{docs_dir}/{dir}"
            if os.path.lexists(dest):
                if not os.path.islink(dest):
                    print(f"-- Skipping {dir} (already exists)")
                    continue
                else:
                    os.remove(dest)
            rel_dir = os.path.relpath(dir, docs_dir)
            rel_dir = f"{rel_dir}/"
            os.symlink(rel_dir, dest, target_is_directory=True)
            print(f"++ Created symlink for {dir}")

    print("You can now implement files from all folders in your repo within the docs")


def main():
    ensure_mkdocs_custom()
    merge_mkdocs_yml()
    ensure_docs_dir()
    sync_managed_docs_assets()
    seed_files()
    ensure_gitignore_entries()
    create_symlinks()


if __name__ == "__main__":
    main()
