site_name: Neops Docs

nav:
  - Start: index.md
#  - Dummy Project: '!include ./submodules/zebbra-mkdocs-dummyproject/mkdocs.yml'

# --8<-- [start:theme]
theme:
  name: material
  custom_dir: docs/override
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - search.highlight
    - content.action.edit
  logo: assets/logo.svg
  favicon: assets/favicon.png

  # Dark and light mode, defaults to system theme
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
# --8<-- [end:theme]

# --8<-- [start:markdown_extensions]
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # Make the build fail if a snippet can't be found.
      check_paths: true
      # https://github.com/mkdocs/mkdocs/issues/2154
      base_path:
        - "mkdocs.yml"
        - "."
#        - "submodules/zebbra-mkdocs-dummyproject"
#        - "submodules/zebbra-mkdocs-dummyproject/docs"
  # Emojy/Symbol/Fontawesome support in markdown
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
# --8<-- [end:markdown_extensions]

# --8<-- [start:plugins]
plugins:
  # Enables search
  - search
  - git-authors
  - git-revision-date-localized
  # Allows to add a whole directory in the navigation instead of just files
  # Sub-nav items are automatically created if the provided dir contains subdirectories
  - include_dir_to_nav
  # Monorepo allows to use the !include in the navigation
  - monorepo

# --8<-- [end:plugins]

# --8<-- [start:repo]
repo_url: https://github.com/zebbra/neops
edit_uri: edit/main/docs
# --8<-- [end:repo]

# --8<-- [start:social]
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://neops.io
      name: Neops
# --8<-- [end:social]

# --8<-- [start:copyright]
copyright: Copyright &copy; Zebbra AG
# --8<-- [end:copyright]