name: Project Management - New Epic
description: Create an epic issue for project management
type: "4-Epic"
labels: []
projects: []
assignees: []
body:
  - type: textarea
    id: issue
    attributes:
      label: Define your epic
      placeholder: Define your epic here...
    validations:
      required: true
