name: Project Management - New Initiative
description: Create an epic issue for project management
type: "5-Initiative"
labels: []
projects: []
assignees: []
body:
  - type: textarea
    id: issue
    attributes:
      label: Define your initiative
      placeholder: Define your initiative here...
    validations:
      required: true
