name: Project Management - New Project
description: Create an epic issue for project management
type: "7-Project"
labels: []
projects: []
assignees: []
body:
  - type: textarea
    id: issue
    attributes:
      label: Define your project
      placeholder: Define your project here...
    validations:
      required: true
