# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  repository_dispatch:
    types: [ trigger ]  # You can specify a custom event type

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true  # Checkout submodules
          token: ${{ secrets.SUBMODULES_TOKEN }}  # Use the GitHub token for authentication
          fetch-depth: 0    # Ensure the full history is fetched (necessary for some workflows)

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Build Project
        run: |
          python -m pip install poetry
          poetry install --directory make_scripts/mkdocs-documentation/
          make update-submodules
          make doc-build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: ./site

  # Single deploy job since we're just deploying
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: site
          path: site
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: cname
        run: echo "docs.neops.io" > site/CNAME
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SUBMODULES_TOKEN }}
          publish_dir: ./site  # Directory with the build artifacts
